version: '3'
services:
    
    db:
        image: postgres:14.5
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        ports: # port exposed to the host machine
            - "5432:5432"
        volumes: # volume used to persist data
            - pgdata:/var/lib/postgresql/data
volumes: # volume creation
    pgdata: {}